# Generated by Django 3.2 on 2022-03-24 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobs',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='userjobs',
            options={'managed': True},
        ),
    ]
