# Generated by Django 3.2 on 2022-03-24 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0002_auto_20220324_0956'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobs',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='userjobs',
            options={'managed': False},
        ),
    ]
