# Generated by Django 3.2 on 2022-03-27 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0003_auto_20220324_1856'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserJobs',
        ),
    ]
