# Generated by Django 3.2 on 2022-03-27 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmploymentStatus', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserEmploymentStatus',
        ),
        migrations.AlterModelTable(
            name='employmentstatus',
            table='EmploymentStatus',
        ),
    ]
