# Generated by Django 3.2 on 2022-03-24 16:56

import HelperClasses.DjangoValidator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_auto_20220324_0956'),
    ]

    operations = [
        migrations.CreateModel(
            name='System',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('system_id', models.AutoField(primary_key=True, serialize=False)),
                ('system_ar', models.CharField(max_length=128, unique=True)),
                ('system_en', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'db_table': 'System',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SystemGroup',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('system_group_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'SystemGroup',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(max_length=14, unique=True, validators=[HelperClasses.DjangoValidator.DjangoValidator.validation_EgyptionMobileNumber]),
        ),
        migrations.AlterField(
            model_name='user',
            name='number_of_identification',
            field=models.CharField(db_column='number_of_identification', max_length=14, unique=True, validators=[HelperClasses.DjangoValidator.DjangoValidator.validation_numberOfIdentintification]),
        ),
    ]
